### ISSUE TITLE
Code meta-dataset

### ISSUE THREAD

**Issue by yangt1013** [cyvius96/few-shot-meta-baseline#10]
Thanks for your code! I have the question about your code in meta-dataset ,How to use it and I can't find your pre-trained model Can you tell me the meaning of this folder code and the code file location of the pre training model, and I look forward to your reply！

**Comment by cyvius96** [comment]
The meta-dataset folder is independent to other parts. The instructions are in its README.md. It does not provide pre-trained model therefore you may want to follow the instructions and run train_classifier.py first.
