### ISSUE TITLE
I can't find the mixup/label smoothing operation

### ISSUE THREAD

**Issue by sailist** [cyvius96/few-shot-meta-baseline#11]
Hi authors, thanks very much for the amazing work. You say that mixup/label smoothing are used in your experiments, but I can't find where it is, would you mind show me the position? If it's not the latest version, I would be appreciate if you can commit your change.

**Comment by cyvius96** [comment]
There is no label smoothing, as emphasized in our paper and this repo.

**Comment by sailist** [comment]
...I wrongly issued in your repo, it's another paper which use these. I'm so sorry about it.
