### ISSUE TITLE
Pretrained models for meta-baseline

### ISSUE THREAD

**Issue by jlindsey15** [cyvius96/few-shot-meta-baseline#14]
Hi!  Thanks for this code.  I was wondering if it would be possible to share pretrained models for the Meta-baseline (not just the Classifier-baseline) on ImageNet-800

**Comment by cyvius96** [comment]
Thanks for your interest. I have no access to the server for training the model currently, but the meta-learning stage would not be too long (several hours) if you start from a converged classifier-baseline.
