### ISSUE TITLE
How to generate the pickle file on my own dataset?

### ISSUE THREAD

**Issue by xqyd** [cyvius96/few-shot-meta-baseline#15]
Can you share the code or script on how to prepare a given dataset into your pickle-style dataset? Thanks a lot!!!

**Comment by cyvius96** [comment]
Those pickle-style datasets are obtained from the reference repos, I didn't generate them by meself. Using `pickle` package to check their format and store your own dataset with the same format should work.

For using your own dataset, it is not necessary to follow the pickle format (e.g. ImageNet-800 uses image folders), you can write your own pytorch data loader. This may help: https://github.com/cyvius96/few-shot-meta-baseline/issues/5

**Comment by xqyd** [comment]
After writing my own code to split and load the corresponding data into base and novel set respectively, I was able to train and test the code successfully. Thanks for your wonderful work!!!

**Comment by cyvius96** [comment]
You're welcome.
