### ISSUE TITLE
The meta-dataset folder

### ISSUE THREAD

**Issue by zl9501** [cyvius96/few-shot-meta-baseline#16]
Hi, thanks for your impressive work! 
I am wondering what is the usage of the folder `meta-dataset`, since it is an independent folder. How and when should I use it?
Should I run "2. Training Meta-Baseline python train_meta.py --config configs/train_meta_mini.yaml" in the `meta-dataset` folder, or in the `few-shot-meta-baseline folder`? It is a little confusing.

**Comment by cyvius96** [comment]
Thanks for your interest in our work.
You should run it in the root folder (i.e. few-shot-meta-baseline). There is no `configs/train_meta_mini.yaml` in the meta-dataset folder.
Meta-dataset is a new dataset proposed recently with its new setting, which is different to mini/tiered ImageNet, it should be an independent folder for experiments on meta-dataset. Note it also has indepent instructions for running the experiments in its README.
