### ISSUE TITLE
Is it possible to use a pretrained model on Classifier-baseline training?

### ISSUE THREAD

**Issue by xqyd** [cyvius96/few-shot-meta-baseline#18]
Just out of curiosity, since my own dataset is quite small, with only 51 classes and each class has less than 100 examples. Do you think it is possible to use a pretrained model, say ResNet18, as the start point to engage the Classifier-Baseline training, then use the trained model for Meta-Baseline training and so on?

I've looked into the code and set the `pretrained=True` in `def resnet18(pretrained=True, progress=True, **kwargs)`. However, the result did not seem to be any difference when `pretrained=False`. Base on the `train_classifier_im800.yaml`, the 
`model_args` is

-  `encoder: resnet18`
- `encoder_args: {}`
- `classifier: linear-classifier `
- `classifier_args: {n_classes: 800}`

It just enlists `resnet18` as the backbone encoder. Can I set `encoder_args` like `encoder_args: {pretrained: true}` or so?

**Comment by cyvius96** [comment]
I am not sure what will the result be if training ResNet-18 from scratch with such a small dataset, data augmentation and proper lr decay may help.
The `pretrained` arg is from Pytorch's original implementation of ResNet, which is used for loading the official ImageNet-1K pretrained model (but not used in our code). If you want a pretrained model, you may need to download the pretrained model from Pytorch's website and load its parameters manually in the code.

**Comment by xqyd** [comment]
Sure. Thanks for your help.
