### ISSUE TITLE
about miniagenet datasets

### ISSUE THREAD

**Issue by 123675** [cyvius96/few-shot-meta-baseline#19]
Hello!
In the train stage of minIageNet datasets, there are 64 types of samples, each of which has 600 samples, which means 38400 samples. If you use the 5-way 1-shot experimental setting, it means that one task requires 80 images and your batch has 200 tasks,
your epoch has 4 batches, which means that 64000 pictures are used, and you used data amplification? Or is the sample reused in one epoch? thank you for your patience!

**Comment by cyvius96** [comment]
Hi.
A task/episode contains 80 images, episodes-per-batch is 4 so each batch contains 4*80 images. Each epoch contains 200 batches.

**Comment by cyvius96** [comment]
Hi. "Epoch" here does not refer to a full loop on the dataset, it is just we call every 200 batches an epoch for convenience.

**Comment by 123675** [comment]
Thank you for your timely reply, but according to your settings, one epoch needs 64000, which is larger than the total number of samples in the training set. Do you mean that there are sample reuse in one epoch? Or is the data amplified and used in one epoch without duplicate samples? thank you

**Comment by cyvius96** [comment]
You're welcome.
Yes, there is sample-reusing. Actually each batch is sampled independently (see datasets/samplers.py), that is, it is draw-with-replacement.

**Comment by 123675** [comment]
Thank you for your patience.
