### ISSUE TITLE
How can I get miniImageNet_category_split_train_phase_train.pickle?

### ISSUE THREAD

**Issue by ZhiZZhang** [cyvius96/few-shot-meta-baseline#2]
I can not run the codes due to the lack of miniImageNet_category_split_train_phase_train.pickle. How can I get it?

**Comment by ZhiZZhang** [comment]
Re-downloading using the provided link solves this problem.

**Comment by Harry-Up** [comment]
> Re-downloading using the provided link solves this problem.

I am sorry that I cannot get the point. Again, how could we get miniImageNet_category_split_{}.pickle files? Thanks!
