### ISSUE TITLE
some questions on meta-training stage

### ISSUE THREAD

**Issue by whySnowwW** [cyvius96/few-shot-meta-baseline#20]
excuse me ,i wonder whether the encoder part of the model is training and update in the meta-learning stage?

**Comment by cyvius96** [comment]
Yes. Actually only the encoder part contains parameters.

**Comment by whySnowwW** [comment]
then,how the gamma update(in the cossine similarity)？

**Comment by cyvius96** [comment]
That's a good point, gamma is an additional parameter.
