### ISSUE TITLE
Q

### ISSUE THREAD

**Issue by brglab839550057** [cyvius96/few-shot-meta-baseline#25]
Hello，I have a Q.During the run, this problem appeared:
No such file or directory: './materials\\mini-imagenet\\miniImageNet_category_split_train_phase_train.pickle'
Expect your help!

**Comment by cyvius96** [comment]
Did you run your code in Linux/MacOS?

**Comment by brglab839550057** [comment]
> Did you run your code in Linux/MacOS?

Win10,and I run in jupyter notebook

**Comment by cyvius96** [comment]
The code was not tested in Windows, you may need to run it in Linux with CUDA.

**Comment by brglab839550057** [comment]
> The code was not tested in Windows, you may need to run it in Linux with CUDA.

Thanks for your help!

**Comment by cyvius96** [comment]
You're welcome.
