### ISSUE TITLE
loss/acc averaging

### ISSUE THREAD

**Issue by fmu2** [cyvius96/few-shot-meta-baseline#6]
In train_meta.py, when the average train/val loss and accuracy get updated, it seems like the argument n in add() should be set to the number of episodes per mini-batch.

**Comment by cyvius96** [comment]
I think it should be equivalent since #episodes per mini-batch is a fixed number. (Please let me know if I am wrong.)

**Comment by fmu2** [comment]
That's right :) Thanks!
