### ISSUE TITLE
Results in Table 11

### ISSUE THREAD

**Issue by fmu2** [cyvius96/few-shot-meta-baseline#7]
Would it be possible to release the config files for cos-metric based training? Thanks.

**Comment by cyvius96** [comment]
Replacing `classifier: linear-classifier` with `classifier: nn-classifier` in train_classifier_xxx.yaml should work. You can cheeck NNClassifier in models/classifier.py for details.

**Comment by cyvius96** [comment]
Replacing classifier: linear-classifier with classifier: nn-classifier in train_classifier_xxx.yaml should work. You can check NNClassifier in models/classifier.py for details.
