### ISSUE TITLE
Testing the model

### ISSUE THREAD

**Issue by MaleshwarSastri** [cyvius96/few-shot-meta-baseline#9]
Hey!
I have trained the model as you mentioned in the repo. I do have the weights file now. Im now stuck at how to evaluate or test my model.How do i feed my query and target image to the model. I ran the test_one_shot.py file as you said.It gave an error like this:
set gpu: 0
dataset: torch.Size([3, 80, 80]) (x12000), 20
num params: 0.0K
Traceback (most recent call last):                                              
  File "test_few_shot.py", line 125, in <module>
    main(config)
  File "test_few_shot.py", line 77, in main
    logits = model(x_shot, x_query).view(-1, n_way)
  File "/home/malesh/anaconda3/envs/att_2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/dash/Alpha_Share/LOGO_POC/RnD/few_shot/few-shot-meta-baseline-master/models/meta_baseline.py", line 31, in forward
    x_tot = self.encoder(torch.cat([x_shot, x_query], dim=0))
TypeError: 'NoneType' object is not callable

How do i rectify this and please provide us with more details on evaluating the model.

**Comment by cyvius96** [comment]
Hi. The log is saying that the model is not loaded. Did you follow the instructions and set load/load_encoder to xxx.pth in configs/test_few_shot.yaml ?

**Comment by MaleshwarSastri** [comment]
Hey! 
Thanks for your reply. This actually worked. Another query is that how should i evaluate the model.That is can i test the model in such a way that if i give a target image i should run the detection with the help of a query image it should detect the object that i desire.

**Comment by cyvius96** [comment]
To test a single image you may need to directly feed it in the code, the current code is only for batch-testing.
